name: React-native-code-push CI

on:
  pull_request:
    branches:
      - master

jobs:
  test-iOS:
    name: Test iOS app
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependecies
        run: npm install
      - name: Install react-native-cli
        run: npm install react-native-cli
      - name: Run tests
        run: npm run test:ios
